version: "3.8"
services:
  terrakube-api:
    image: azbuilder/api-server:2.17.0
    ports:
      - 8080:8080
    env_file:
      - api.env
  terrakube-ui:
    image: azbuilder/terrakube-ui:2.17.0
    ports:
      - 3000:8080
    volumes:
      - ./env-config.js:/app/env-config.js
    env_file:
      - ui.env
  terrakube-executor:
    image: azbuilder/executor:2.17.0
    ports:
      - 8090:8090
    env_file:
      - executor.env
  terrakube-registry:
    image: azbuilder/open-registry:2.17.0
    ports:
      - 8075:8075
    env_file:
      - registry.env
  terrakube-dex:
    image: ghcr.io/dexidp/dex:v2.37.0
    volumes:
      - ./config-ldap.yaml:/etc/dex/config.docker.yaml
    ports:
      - 5556:5556
  ldap-service:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ORGANISATION: "Example, Inc"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
    volumes:
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    ports:
      - 389:389
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    command: "server -s3 -s3.port=9000 -dir=/data"
    ports:
      - '9000:9000'
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin
    volumes:
      - 'seaweedfs_data:/data'
  seaweedfs-init:
    image: chrislusf/seaweedfs:latest
    depends_on:
      - seaweedfs
    entrypoint: [ "/bin/sh", "-c", "sleep 3; echo 's3.bucket.create -name sample' | weed shell -master=seaweedfs:9333; exit 0;" ]
  redis-service:
    image: valkey/valkey:8-alpine
    command:
      - valkey-server
      - --requirepass
      - password123456
      - --rename-command
      - FLUSHDB
      - ""
      - --rename-command
      - FLUSHALL
      - ""
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.42
    ports:
    - 6831:6831/udp
    - 6832:6832/udp
    - 16686:16686
    - 14268:14268
    - 14250:14250

volumes:
  seaweedfs_data:
  redis_data: